### ISSUE TITLE
Error running the MKL.m

### ISSUE THREAD

**Issue by krishnasubiyanto** [bcnmedtech/unsupervised_multiple_kernel_learning#1]
Hy,

I just download the code and try running the program using the Synthetic_velocities.mat dataset. The program stop running at MKL.m and show error message :

Error using MKL (line 231)
Requested 429496729700x72360521 (17179869184.0GB) array
exceeds maximum array size preference. Creation of
arrays greater than this limit may take a long time and
cause MATLAB to become unresponsive. See array size
limit or preference panel for more information.

Error in Launch_MKL (line 77)
[F_data,~,~] = MKL(FEATURES,options);

is there anyway to solve the problem?

I have download CVX toolbox and run the mex command and using MATLAB R2018a

Thank you

**Comment by nicolasduchateau** [comment]
Hi, sorry for the late reply.
This comes from the call to the .mex functions computeSWA, computeSWB, and computeENERGY.
It's rather easy to solve: just delete the compiled mex files (.mexa64) and run "mex(filename.c,'-compatibleArrayDims')" for each of these three .c files.

**Comment by krishnasubiyanto** [comment]
Thank you for your reply. 
I tried it and it solved the problem.
